spring:
  server:
    port: 8011
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: test
    port: 25
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

api:
  security:
    token:
      secret: test

google:
  secrets:
    clientId: test
    clientSecret: test
  url:
    oauth: test
    userInfo: test

frontend:
  url: test

mail:
  from: test@example.com

password-reset:
  token-ttl-minutes: 30
  cooldown-minutes: 1

cookie:
  secure: false

cors:
  allowed-pattern: http://localhost:3000
