spring:
  server:
    port: 8011
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

api:
  security:
    token:
      secret: test

google:
  secrets:
    clientId: test
    clientSecret: test
  url:
    oauth: test
    userInfo: test

frontend:
  url: test